import os
from os import getenv
from dotenv import load_dotenv

load_dotenv(".env")
load_dotenv(".env1")
load_dotenv(".env2")
load_dotenv(".env3")
load_dotenv(".env4")
load_dotenv(".env5")
load_dotenv(".env6")
load_dotenv(".env7")
load_dotenv(".env8")
load_dotenv(".env9")
load_dotenv(".env10")
load_dotenv(".env11")
load_dotenv(".env12")
load_dotenv(".env13")
load_dotenv(".env14")
load_dotenv(".env15")
load_dotenv(".env16")
load_dotenv(".env17")
load_dotenv(".env18")
load_dotenv(".env19")
load_dotenv(".env20")
load_dotenv(".env21")
load_dotenv(".env22")
load_dotenv(".env23")
load_dotenv(".env24")
load_dotenv(".env25")
load_dotenv(".env26")
load_dotenv(".env27")
load_dotenv(".env28")
load_dotenv(".env29")
load_dotenv(".env30")
load_dotenv(".env31")
load_dotenv(".env32")
load_dotenv(".env33")
load_dotenv(".env34")
load_dotenv(".env35")

API_ID = int(getenv("API_ID", "22156937"))

API_HASH = getenv("API_HASH", "0f8f66b06b1c53b9263bcfb1123e9c85")

BOT_TOKEN = getenv("BOT_TOKEN", "")
